channels:
  - defaults
dependencies:
  - notebook
  - matplotlib
  - gymnasium
  - torchaudio
  - torchvision
  - pytorch-cuda=11.8
  - tqdm
  - scikit-learn
  - conda=25.3.1
  - pytorch
  - cloudpickle
  - python=3.10
  - tensorboard
  - pandas
  - ipywidgets
  - numpy
  - scipy
  - openpyxl
